# Generated by Django 2.0.3 on 2018-03-08 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shoppingcart',
            fields=[
                ('shoppingcart_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('last_updated_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(0, 'Pending Checkout'), (1, 'Processing'), (3, 'Checked out')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='shoppingcartitems',
            fields=[
                ('shoppingcartitem_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('shoppingcart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scapi.shoppingcart')),
            ],
        ),
        migrations.CreateModel(
            name='shoppingcartuser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppingcart', to='scapi.shoppingcartuser'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcartitems',
            unique_together={('shoppingcart_id', 'item_id')},
        ),
    ]
